# Generated by Django 3.2.5 on 2021-07-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
