# Generated by Django 3.2.5 on 2021-07-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_review_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='create_at',
            new_name='createTime',
        ),
    ]
